### ISSUE TITLE
Layout inside antoher layout 0.4

### ISSUE THREAD

**Issue by EstebanVignon** [Pilot-in/PiloPress#108]
**Describe the bug**
When I click on the layout, modal not display, just a grey overlay.

**Screenshots**
![image](https://user-images.githubusercontent.com/28347143/106719675-e1d91480-6602-11eb-90f3-cd3948eba039.png)

**WordPress, Plugins**
WordPress version:
Pilo'Press version: 0.4
ACF Pro version:
ACFE version:
ACF add-ons:

**Comment by damien-pilot-in** [comment]
The issue was layout based.
