### ISSUE TITLE
Change "Classes à appliquer" text field with textarea field

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress#116]
**Is your feature request related to a problem? Please describe.**
It's not really practical when you have a lot of classes.

![image](https://user-images.githubusercontent.com/62112531/107035633-c44dab80-67b8-11eb-93f1-198e13381ecb.png)

**Comment by michael-dev-pilotin** [comment]
See --> https://github.com/Pilot-in/PiloPress/tree/pilopress-textarea-button-class
