### ISSUE TITLE
No standard layouts

### ISSUE THREAD

**Issue by Criggz97** [Pilot-in/PiloPress#119]
Hello!
I am interested in your plugin. I just wonder if it comes with some premade layouts? When I installed the layouts folder was empty. :)

Just wonder so nothing got messed up in the installation process.

**Comment by damien-pilot-in** [comment]
Hello @Criggz97,
Thank you for your interest!

We're preparing a standard pack with few layouts _(enough to make a landing)_
to make it easier to understand how the Pilo'Press works.
It's coming in the next few days :)

Stay tuned!

**Comment by Criggz97** [comment]
Sounds good!
It's nice to have some layout to see how you recommend us using the plugin! 🥇

**Comment by damien-pilot-in** [comment]
Hey there!
We made a public repo with basic layouts to use with the Pilo'Press so you can see how it works :)
- [Pilo'Press Public Layouts](https://github.com/Pilot-in/PiloPress-Public-Layouts)
