### ISSUE TITLE
Prefix Color Fields Value with #

### ISSUE THREAD

**Issue by michael-dev-pilotin** [Pilot-in/PiloPress#131]
When we select a color on Zeplin it select only the value without the Hashtag.
Maybe we can use a prefix in the field to prevent manually adding the hashtag before value.

![Capture d’écran 2021-04-09 à 16 32 43](https://user-images.githubusercontent.com/62141851/114195965-383f3800-9951-11eb-894a-a9c1b826f97e.png)
![Capture d’écran 2021-04-09 à 16 31 33](https://user-images.githubusercontent.com/62141851/114195988-3c6b5580-9951-11eb-816e-75573249d0b6.png)

**Comment by damien-pilot-in** [comment]
It's needed sometimes to have non-hexadecimal value, so we can't really do that unfornatunately.
