### ISSUE TITLE
PIP_Flexible not available in option pages

### ISSUE THREAD

**Issue by barnemax-pilotin** [Pilot-in/PiloPress#137]
**Describe the bug**
The flexible won't show up in option pages while setting locations rules to the said option page (Editor page) + having a layout with the option page in location rules as well.

**To Reproduce**
Create option page via ACFE or PHP, set locations rules of the flexible to the created option page, have layout with similar locations rules --> check option page

**Expected behavior**
The flexible to appear in option page

**Screenshots**

![2021-05-20_16h43_23](https://user-images.githubusercontent.com/62242698/118999618-b77d4e00-b98a-11eb-8f2c-1668d3586048.png)

![2021-05-20_16h43_33](https://user-images.githubusercontent.com/62242698/118999638-bc420200-b98a-11eb-929e-20153b760862.png)

![2021-05-20_16h44_14](https://user-images.githubusercontent.com/62242698/118999667-c237e300-b98a-11eb-9445-d7a2ea9ed027.png)

![2021-05-20_16h44_41](https://user-images.githubusercontent.com/62242698/118999684-c532d380-b98a-11eb-8e55-2868fbf2c3eb.png)

**WordPress, Plugins**
Latest version WP and ACF/ACFE
PHP 7.4

**Comment by maelys-pilotin** [comment]
Note: When `menu_slug` and `post_id` have the same value, it seems to work

**Comment by maelys-pilotin** [comment]
Fixed
