### ISSUE TITLE
Hidden layouts (ACFE Layout toggle feature) mess with others layouts settings field groups values

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress#138]
**Describe the bug**
Hidden layouts (ACFE Layout toggle feature) mess with others layouts settings field groups values.

**To Reproduce**
- Add many layouts in a post (like 8-10) which have some settings field groups.
- Hide a layout (untoggle) in the early position (2 or 3).
- Save the page and check in front.
- You should have some layouts below the hidden layout which doesn't have their settings values output.

**Expected behavior**
Hidden layout above in my post edition shouldn't interfere with layouts below in front.

**Screenshots**

One of the layouts (2nd layout in my post) i hide using the toggle feature.    

![image](https://user-images.githubusercontent.com/62112531/119159397-7606a480-ba57-11eb-9711-f60bfb2468f0.png)

A layout (4 or 5 layouts below the one hidden) in front which doesn't get values from settings field group.    
_(in this example, it's the background-color value which is empty)_

![image](https://user-images.githubusercontent.com/62112531/119159549-a0586200-ba57-11eb-99e6-37aa0841e57f.png)

In the preview, it does work fine tho'.   

![image](https://user-images.githubusercontent.com/62112531/119159645-bd8d3080-ba57-11eb-8100-4c3f11098706.png)

**WordPress, Plugins**
WordPress version: any
Pilo'Press version: 0.4
ACF Pro version: latest
ACFE version: any

**Comment by maelys-pilotin** [comment]
@damien-pilot-in I can't reproduce. Does it still occurs ?

**Comment by damien-pilot-in** [comment]
It was an issue in ACFE, it will be fixed in next patch, meanwhile we can fix it this way:

In the file: `/acf-extended-pro/includes/fields/field-flexible-content-actions.php  line:415`
Add the following code (before the return $value;):
`$value = array_values($value);`
