### ISSUE TITLE
Error on style build process

### ISSUE THREAD

**Issue by papazetis** [Pilot-in/PiloPress#232]
I am getting the following error when I am updating and building styles

`Fatal error: Uncaught Error: Cannot use object of type stdClass as array
in D:\laragon\www\pilopress\wp-content\plugins\pilopress\includes\views\styles-admin-page.php on line 86
`

**WordPress, Plugins**
WordPress version: 6.1.1
Pilo'Press version: 0.4.3.1
ACF Pro version: 6.0.7
ACFE version: 0.8.9
ACF add-ons: None

![image](https://user-images.githubusercontent.com/3592665/217889931-108f11f0-d7ab-4c56-8c8a-c67f134dc63f.png)

**Comment by jerome-pilotin** [comment]
Hello @papazetis 

Can you please share your PHP version and the Tailwind config you are using to compile?

This particular error tells us the error returned by the Tailwind compilation is malformed (or at least unexpected), and it is tripping up PHP.

**Comment by papazetis** [comment]
Hi @jerome-pilotin 

The problem seems it is fixed when I added an empty `tailwind.config.js` file into `pilopress` folder

![image](https://user-images.githubusercontent.com/3592665/218059156-4211f745-1ed0-48db-9689-aec4b4ae402b.png)

**Comment by jerome-pilotin** [comment]
@papazetis If you are still at the init stage of your project, @Armand-pilotin reminded me that you need to go over each tab and "Save" once before launching the Compilation. Until each tab is saved, there's missing data in the Tailwind config and the Compilation then bugs out.

We will work on improving this behavior

**Comment by papazetis** [comment]
@jerome-pilotin
Thanks for the update.
Yes I am on the init. I saved each tab and removed the tailwind.config.js and it still works fine.
