### ISSUE TITLE
In the layouts screen 'add new' button is hidden

### ISSUE THREAD

**Issue by fgdaniel** [Pilot-in/PiloPress#235]
**Describe the bug**
If I add a layout (only one), the 'add new' button no longer appears if I want to add another layout

**To Reproduce**
Pilo'Press > Layouts > Add new > save, back to screen layouts 'add new' vanish

**Expected behavior**
The add new button must be there always. 

**Screenshots**
[https://imgur.com/3JqRLn4](https://imgur.com/3JqRLn4)

**WordPress, Plugins**
WordPress version: 6.1.1
Pilo'Press version: 0.4.3.1
ACF Pro version: 6.0.7
ACFE version: 0.8.9.2
ACF add-ons: none

**Comment by barnemax-pilotin** [comment]
Hi,

Indeed, we fixed the problem in this commit : https://github.com/Pilot-in/PiloPress/commit/ff1e79e67cf9abd6ce5e1fce4b087d8a094f44da#diff-480e4b52bf9e25a6024e4d81e3ca1ef5ab570dfca5f5255c734872914acfec2c

but it isn't applied to the released version yet, we will work on that soon.

Feel free to get the files from the commit in the meantime.

Thanks for the feedback!

**Comment by fgdaniel** [comment]
Thanks, i use from commit!

**Comment by barnemax-pilotin** [comment]
Fixed in Pilo'Press - 0.4.3.2
