### ISSUE TITLE
Separate @import and custom CSS

### ISSUE THREAD

**Issue by michael-dev-pilotin** [Pilot-in/PiloPress#35]
We can maybe separate in two columns the @import modules code editor from /Styles page and the custom CSS made by the user.

I don't know if most of the people will modify the @import in this code editor, but another idea is to add a checkbox with a warning and unlock the field if the person really want to modify this.

**Comment by maelys-pilotin** [comment]
Regarding Tailwind organization, it's not really interesting to split CSS field in two
