### ISSUE TITLE
Additional location conditions for field type "Component"

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress#41]
Add **more conditions** to the field type "**Component**" 
_(to have more flexibility / dynamism on field group's display)_

![Example](https://user-images.githubusercontent.com/62112531/79732337-d4f96780-82f3-11ea-8185-26d0e9b686ce.png)

We could add some `contains` location condition.

**Comment by maelys-pilotin** [comment]
Added for Pilo'Press 0.4.0
