### ISSUE TITLE
Use Flexible mirror location as default location for new layout

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress#49]
By default, when you create a new layout, it's automatically set to "Post".

It would be nice if we could grab the flexible mirror location configuration and then set it by default on new layout location.

**Comment by Pilotin** [comment]
Layout conditional logic is used as a second layer of conditional logic (on top on the general Flexible Content conditional logic). I'm not sure that Layout should have reflect Flexible Content conditional logic, as they can change over time
