### ISSUE TITLE
Main flexible is displayed on "Site template" when location is set to "post_type_archive" == "all"

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress#77]
**Describe the bug**
Main flexible is displayed on "Site template" when location is set to "post_type_archive" == "all"

**To Reproduce**
Add the following hook:
```php
<?php
add_filter( 'pip/builder/locations', 'pip_flexible_locations' );
function pip_flexible_locations( $locations ) {

    $locations[] = array(
        array(
            'param'    => 'post_type_archive',
            'operator' => '==',
            'value'    => 'all',
        ),
    );

    return $locations;
}

```

**Expected behavior**
Main flexible shouldn't be displayed here.

**Screenshots**
![Annotation 2020-09-02 155913](https://user-images.githubusercontent.com/62112531/91993442-ab3a5d80-ed35-11ea-8823-d8030c9519f9.png)

**Comment by maelys-pilotin** [comment]
Found that the bug is coming from ACF Extended
Waiting for fix

**Comment by maelys-pilotin** [comment]
Seems to be OK after ACFE version 0.8.7.5
