### ISSUE TITLE
Being able to add a limit to layouts

### ISSUE THREAD

**Issue by Pilotin** [Pilot-in/PiloPress#82]
Hello!

It would be useful to limit the number of times a layout is available on a page. With ACF, this can done using the min/max setting on each layout ([See Screenshot](https://i.imgur.com/WEolFUV.jpg)). However in Pilo'Press this setting isn't available per layout. Using `acf/prepare_field` doesn't works, since `get_field_group_visibility()` get all layouts and hide them in the background.

So if a field group layout has a `min` set to `1` using `acf/prepare_field`, but this layout isn't supposed to be displayed on a page (using the built-in field group layout location), it will be still processed in the background and the page couldn't be saved.

**Comment by maelys-pilotin** [comment]
Waiting for ACFE to fix double error badge

**Comment by maelys-pilotin** [comment]
Fixed for version 0.4.0
