### ISSUE TITLE
pip_get_formatted_post_id() doesn't return the id on custom post_type archive in get_pip_content()

### ISSUE THREAD

**Issue by barnemax-pilotin** [Pilot-in/PiloPress#87]
**Describe the bug**
`pip_get_formatted_post_id()` doesn't return the id on custom post_type archive in `get_pip_content()` causing the flexible not to be displayed. EDIT : Only happens when there is no post in the said post_type.

The problem is at `pilopress/includes/helpers.php` l.69 and 70. The function `get_post_type` returns false. It can be changed by `get_queried_object()->name` to get the slug of the post_type.

Demo : [Vidéo](https://www.loom.com/share/1672a36ad40747c6980800c1989c68a3)

**To Reproduce**
Having a custom post type created with ACFE having the archive enabled and adding the archive post_type in the editor page of the PiloPress (and having at least one layout with this archive in the location). EDIT : not having post in the said post_type.

**Expected behavior**
The flexible of the archive page to be called.

**WordPress, Plugins**
WordPress version: 5.5.1
Pilo'Press version: 0.3.2.10
ACF Pro version: 5.9.1
ACFE version: 0.8.7.4
ACF add-ons:

**Comment by maelys-pilotin** [comment]
Fixed for version 0.4.0
