### ISSUE TITLE
Layouts row actions doesn't appear until you have atleast 1 synchronised layout

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress#94]
**Describe the bug**
Layouts row actions doesn't appear until you have atleast 1 synchronised layout.
It seems the "Sync" view inherit from the main "layouts" view and then doesn't render the row actions.

**To Reproduce**
- Add layouts inside your `layouts` folder in your theme.
- Go to PiloPress > Dispositions > Sync
- You have many layouts showing but no row actions.

**Expected behavior**
Row actions should appear when you have row elements.

**Screenshots**
![image](https://user-images.githubusercontent.com/62112531/99544482-a724f000-29b4-11eb-88eb-01953b167562.png)
![image](https://user-images.githubusercontent.com/62112531/99544588-c4f25500-29b4-11eb-9184-489531a343e6.png)

**Comment by maelys-pilotin** [comment]
@damien-pilot-in This is an ACF bug, there's the same problem with field groups
Since layouts are field groups, I can't fix that
